### ISSUE TITLE
Openelec freezes

### ISSUE THREAD

**Issue by RoosterX** [OpenELEC/OpenELEC.tv#3732]
As far back as I can remember I've had this problem that Openelec freezes, picture and sound freezes(no sound), but subtitles continue. Takes a long while to stop this, push stop button on remote and it takes probably 30 seconds or so until I get menu back.

This happens sometimes not for weeks, then it could occur every 10 minutes or so, or different interval.

In log below it froze 2 times.

http://xbmclogs.com/show.php?id=385388

**Comment by yevgenybezman** [comment]
Having the exact same issue.
My media is stored on a windows 7 share on a PC connected through a wireless network.
Whenever the connection has a problem, kodi freezes completely for quite a while. Need to restart the computer to fix it completely.

**Comment by ramonderuiter** [comment]
Same here on an intel NUC playing via NFS. Only seems to happen when i resume playing after a pause. 
[Logs](http://www.megafileupload.com/en/file/596769/log-2015-01-09-22-24-00-zip.html)

**Comment by ramonderuiter** [comment]
This one should be more helpful.
[Kodi debug log] (http://www.megafileupload.com/en/file/597050/kodi-subtitle-hang-log-zip.html)

**Comment by ramonderuiter** [comment]
It's actually easy to reproduce it seems. Keeping a playing video paused for say 15 minutes and then resuming it results in the described behaviour. Stopping the playing video is impossible, i have to reboot the NUC in order to get rid of the hang.
@fritsch Do you need more logfiles?

**Comment by fritsch** [comment]
Nope. My every day job started again - I have no time to fix that and furthermore I also don't have an idea on what could be done.

**Comment by ecser99** [comment]
I have the same problem. With almost every video I play (on a NUC over LAN from a Synology / SMB):
"picture and sound freezes(no sound), but subtitles continue. Takes a long while to stop this, push stop button on remote and it takes probably 30 seconds or so until I get menu back."
Sometimes it just craches (ne freeze) during a film and goes out int the menu.
Log:
http://www.megafileupload.com/en/file/613767/log-2015-03-01-06-22-39-zip.html

**Comment by pavlos256** [comment]
This sounds like the problem I've reported [on the forum](http://openelec.tv/forum/107-suspend-and-wakeup/74555-no-audio-freeze-after-standby-on-5-0-4-2-1-ok).

Can you confirm? Does suspend/wake solve it temporarily?

**Comment by fritsch** [comment]
When your TV is off when the NUC switches on - where should it know what it
is connected to? HDMI has hotplug detection, if nothing is connected, e.g.
OFF - video output / audio output won't work. Make 100% sure all components
are on and running before you resume from suspend.

Baytrail freezes, especially with quad core BYT systems are kernel related
- intel seems to work on that.

2015-03-04 18:25 GMT+01:00 Pavlos Touboulidis <notifications@github.com>:

> This sounds like the problem I've reported on the forum
> <http://openelec.tv/forum/107-suspend-and-wakeup/74555-no-audio-freeze-after-standby-on-5-0-4-2-1-ok>
> .
>
> Can you confirm? Does suspend/wake solve it temporarily?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/3732#issuecomment-77203181>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by pavlos256** [comment]
The TV is never off. The problem happens *after leaving the player idle* for a while (video paused or after playback has finished). Everything works fine when it wakes up, navigation, etc, all works as expected except that when starting play back again, the video plays for a few seconds without audio and then the screen freezes. The system is still working - hitting stop will return to the menu 20 seconds later.

**Comment by fritsch** [comment]
Ah, that's a nicer bug :-) Don't forget your logfiles - especially in debug mode it should reveal something.

**Comment by pavlos256** [comment]
[Logs](http://uploadfiles.eu/vh161l03q884/log.zip.html).

You can see the first playback at 09:06:27, and the second at 09:45:58.

```
09:06:14 T:140038673045248  NOTICE: Thread BackgroundLoader start, auto delete: false
09:06:27 T:140039962584960  NOTICE: Previous line repeats 1 times.
09:06:27 T:140039962584960  NOTICE: DVDPlayer: Opening: /storage/videos/test.mp4
...
09:45:47 T:140039952029440   ERROR: ActiveAE::InitSink - failed to init
09:45:58 T:140039962584960   ERROR: Previous line repeats 1 times.
09:45:58 T:140039962584960  NOTICE: DVDPlayer: Opening: /storage/videos/test.mp4
```

**Comment by fritsch** [comment]
I cannot click on the logs, please use sprunge, paste.ubuntu.com, xbmclogs.com whatever - from your snippet, there is a problem with the audio device - most likely gone.

**Comment by pavlos256** [comment]
None of these allows uploading the ZIP file that OpenELEC creates in /storage/logfiles.

I've uploaded KODI.log [here](http://sprunge.us/FjRC). Let me know if you need another file.

Thanks!

**Comment by fritsch** [comment]
Please provide a debuglog, so that I can see which device it tries.

2015-03-05 10:28 GMT+01:00 Pavlos Touboulidis <notifications@github.com>:

> None of these allows uploading the ZIP file that OpenELEC creates in
> /storage/logfiles.
>
> I've uploaded KODI.log here <http://sprunge.us/FjRC>. Let me know if you
> need another file.
>
> Thanks!
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/3732#issuecomment-77332317>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by pavlos256** [comment]
Done. See [line 837](http://sprunge.us/Ogej?text#n-837) for the DPMS suspend, the problem starts a few lines after when it wakes up and tries to play the video.

**Comment by fritsch** [comment]
@FernetMenta Do you have an idea what is causing this under the hood? The ALSA hotplug patches don't seem to register a change and the device seems just gone ...

**Comment by FernetMenta** [comment]
I would say the problem starts with line 843
CAESinkALSA - HDMI device "hdmi:CARD=PCH,DEV=0" may be unconnected (no ELD data)
after that we try to open an unconnected device which might make ALSA fail. git blame shows
https://github.com/FernetMenta/xbmc/commit/fb9af19585820ce1827ffb320a97faf04933f2ad

and the winner is @fritsch :)

**Comment by pavlos256** [comment]
I don't know if it helps, this problem didn't manifest itself in 4.2.1.

**Comment by fritsch** [comment]
@FernetMenta We still have a lot of devices that don't show ELD info at all ... What makes me wonder is, that th device disappears - do we know why?

**Comment by fritsch** [comment]
Ah wait!

it gets dpms - ALSA sink reinitializes- then it resumes - ALSA does not this event and we end up in a broken state.

**Comment by FernetMenta** [comment]
now we are in a state where all those work arounds ruined the happy path. it is wrong to open an unconnected HDMI device. further the idea of having the device change event is that audio can switch to another device automatically. when you pull the HDMI plug audio should switch.

**Comment by fritsch** [comment]
I cannot see a solution, if my original commit is reverted, that will end up all users without HDMI handshake (e.g. ION-1 by design, amd fglrx, etc.) completely without hdmi audio.

I rather think, we should take care that on DPMS resume a rescan is done - as the device is disabled when dpms turns on.

What do you want to do?

**Comment by FernetMenta** [comment]
I would add and advanced setting to enable the work arounds for that old crap and treat other systems the normal way.

**Comment by fritsch** [comment]
So in the use case we see here:

The DPMS would kick in, as the TV is off - the HDMI 0 would be invalidated and removed. After the TV turns back on - there is _no_ event, so that device would never come back.

An advancedsetting would not solve this issue. We need to find out why DPMS resume does not trigger the rescan.

**Comment by FernetMenta** [comment]
the first action which is incorrect is opening a disconnected device against the hints of the driver. What happens after this may already be follow-up errors. in a perfect world the driver would cope with this but it is not perfect. you may sacrifice one behavior for another.

**Comment by fritsch** [comment]
Whatever you want - we can do -> I don't have the time currently to get a whole lot of spam mails by users for "my sound device is gone"  or "my hdmi audio device always resets to Analog Audio when DPMS sets in"

**Comment by WedgeSparda** [comment]
Having the same issue here. 
Randomly the playback stops and Kodi doesn't react to my TV remote. 
Sometimes, after a long wait, playback closes and I can resume it.

Anything new?

**Comment by fritsch** [comment]
No - your issue is something totally different. Don't highjack other issues, please - the former poster has a problem with the Audio device disappearing, nothing else.

**Comment by WedgeSparda** [comment]
Sorry

**Comment by RoosterX** [comment]
This is my  dmesg | pastebinit http://sprunge.us/IWPc

After a freeze.

**Comment by chewitt** [comment]
closing due to length of time with no update
