### ISSUE TITLE
Raspberry Pi 2, poor streaming performance.

### ISSUE THREAD

**Issue by bircoe** [OpenELEC/OpenELEC.tv#3886]
Raspberry Pi 2 running OE 5.0.1
Buffer fails to keep up with files that have bitrates in excess of 25Mbps. Large files will play for approx 10-15 seconds till the buffer empties then pause while the buffer refills, I have built r20209 from source and the same issue occurs albeit not quite as bad.

This build completely fixes the issue and during playback of a 38GB bluray rip the buffer stays at ~99% indefinitely.
OpenELEC-RPi2.arm-Milhouse-20150206210325-r20209-g4c075fb.tar

The above build uses Kodi 15.0-ALPHA1 Git:03ff9dd.

I have confirmed the same symptoms on 2 Pi2's updating both of them to the Millhouse build fixes it.
The below thread also confirms the issue:
http://openelec.tv/forum/124-raspberry-pi/75117-rasbperry-pi-2-problem-large-mkv-dvblink-1080i

KODI.log:
http://sprunge.us/PYcR
In the above log the file is opened at line 21:35:12 T:3043196928, I left it running for approx 45 seconds before stopping the video, during that time there were 3 pauses for the buffer to catch up, there doesn't seem to be any log entries to indicate that.

KODI.log - Debug:
http://sprunge.us/CKVd
In the above log the file is opened at line 10:00:30 T:3043807232, again I left it running for approx 45 seconds stopping the video on the 4th buffer pause. There are numerous entries in the above linked log that look like this:
10:00:36 T:2727146560   DEBUG: OMXClock::OMXSetSpeed(0.00) pause_resume:1
10:00:36 T:3024262208   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
10:00:36 T:3024262208   ERROR: CCurlFile::CReadState::Connect, didn't get any data from stream.
10:00:36 T:3024262208   DEBUG: CurlFile::Open(0xb4428ce8) http://feeds.xbmc.org/latest_xbmc_addons
10:00:37 T:2727146560   DEBUG: CDVDPlayer::OMXDoProcessing Resume 0.88,0.88 (A:01 V:01) EOF:0 FULL:0 T:0.80

I have tested both via SMB and NFS, the issue occurs regardless. My network consists entirely of gigabit switches with files stored on a HP MicroServer, there is no performance issue in my network, there is plenty of throughput. To confirm this I SCP'd a file from the NAS via the RPi2, the file was 100MB and completed in 10 seconds at 9.5MB/s (76 Mbps) which is more than enough to stream a file with a bitrate of 25Mbps.

**Comment by fritsch** [comment]
Please read our github documentation before opening issues here. You did not post a single log the contributing link needs. Until you add those, I will mark this as invalid.

**Comment by fritsch** [comment]
Also, we need to distinguish "generic" issues and specific issues. @MilhouseVH latest build includes a testing patch I did for libnfs to read 1MB chunks. This does not affect samba or any other streaming.

Therefore, describe your issues, describe your network installation at home and provide a debuglog of the failing issue.

**Comment by popcornmix** [comment]
With OE 5.0.1 can you try adding to config.txt:
```
device_tree=
```
and report if it helps?

**Comment by bircoe** [comment]
Updated with more info, could this possibly be related to https://github.com/OpenELEC/OpenELEC.tv/issues/3866 ?

Just device_tree= ?Nothing after the =?

**Comment by fritsch** [comment]
According to other reports: http://forum.kodi.tv/showthread.php?tid=211501&pid=1916745#pid1916745 <- is the first build that makes it work and the builds before it also don't work.

@bircoe Is that also the case for you?

Not working: http://forum.kodi.tv/showthread.php?tid=211501&pid=1915540#pid1915540
Working: http://forum.kodi.tv/showthread.php?tid=211501&pid=1916745#pid1916745

Thanks much for testing.

**Comment by popcornmix** [comment]
Yes "device_tree=" unsets the device_tree value, hence disabling it.

**Comment by fritsch** [comment]
@bircoe I had the "not working link" wrong in the above post - if you already tested that - both should have been working.

**Comment by bircoe** [comment]
device_tree= causes the Pi to not boot, it just stops at the screen with the coloured test pattern.
OpenELEC-RPi2.arm-Milhouse-20150205210924-r20204-g4f46e9a - Working
OpenELEC-RPi2.arm-Milhouse-20150203210258-r20194-gfa82a48 - Not working

For reference I also built the current build (r20209) during the day and that has the same buffer issue.

I'd be happy to have another go at building if you can give me a pointer as to how to revert curl.

**Comment by fritsch** [comment]
https://dl.dropboxusercontent.com/u/55728161/OpenELEC-RPi2.arm-devel-20150208125452-r20216-g499c0f1.tar <- what happens here?

**Comment by fritsch** [comment]
One moment! this has downgraded libcurl, but I did not rebuild kodi against it.

**Comment by bircoe** [comment]
It's better, but the buffer still runs out, it goes for a minute or so now as opposed to 10-15 seconds.
With r20204-g4f46e9a the buffer is pegged at ~99%.

**Comment by fritsch** [comment]
Okay, here we go: https://dl.dropboxusercontent.com/u/55728161/OpenELEC-RPi2.arm-devel-20150208133539-r20216-g499c0f1.tar

**Comment by bircoe** [comment]
Nope, still runs out.

**Comment by fritsch** [comment]
Good, then we had luck and this was not a libcurl issue. I will post a libcurl 7.40.0 build with the referenced hack in 3 minutes - to make a final test, please.

@popcornmix we should follow the idea you told over at the forum. Which changes are needed for OpenELEC master to compensate those 10 ms sleeps?

@bircoe So one final build from me in three minutes.

**Comment by popcornmix** [comment]
@fritch - 
bumping kernel to latest and rebuilding should fix it.
disabling device tree with "device_tree=" should fix it

I suspect updating the board dtb file would fix it. e.g. download
https://github.com/raspberrypi/firmware/raw/master/boot/bcm2709-rpi-2-b.dtb

and replace the one on boot partition of sdcard (e.g. in /flash)

**Comment by fritsch** [comment]
@sraue: ping ^^ this we need for our stable branch.

@bircoe Just for completion: https://dl.dropboxusercontent.com/u/55728161/OpenELEC-RPi2.arm-devel-20150208135100-r20217-g9d4849b.tar

**Comment by fritsch** [comment]
@popcornmix thx very much, will look into it tonight - need to travel again :-( thx much

**Comment by bircoe** [comment]
That build still doesn't fix it, buffer runs out after a minute or so.

**Comment by bircoe** [comment]
But, replacing the dtb file does fix it!

The file popcornmix linked resolves the issue entirely.
cffd04f5c9f3a883cbcc8caf5b2fac4e  bcm2709-rpi-2-b.dtb

I'll reload 5.0.1 and see if the dtb file fixes it there aswell.

**Comment by gdachs** [comment]
device_tree= in config.txt with latest release from fritsch fixed it for me too.

**Comment by bircoe** [comment]
Confirmed, replacing the dtb file on 5.0.1 resolves the issue, I have not added the device_tree line to the config.txt either.

So this issue is firmware related and I can only assume will be solved in the next release.

Sorry for leading you down the wrong path with the curl stuff fritsch.

**Comment by popcornmix** [comment]
Thanks for testing @bircoe.
I think the recommended fix is updating the bcm2709-rpi-2-b.dtb.
And hopefully this will be included in a 5.0.2 build soon.

**Comment by sraue** [comment]
can you test also http://snapshots.openelec.tv/OpenELEC-RPi2.arm-devel-20150208133726-r20229-g77697ca.tar this is a build from our master with updated kernel which i will backport to 5.0 for 5.0.2. curl is the same like in 5.0.x will create a updated openelec-5.0 testbuild later

**Comment by sraue** [comment]
^^^ test without device_tree= in config.txt

**Comment by bircoe** [comment]
That indeed resolves the issue. Thank you.

**Comment by fritsch** [comment]
Thx much to all involved for testing and @popcornmix for the solution.
Am 08.02.2015 14:37 schrieb "bircoe" <notifications@github.com>:

**Comment by bircoe** [comment]
For completeness sake the issue is not present in 5.0.2.

Thank you.
